# Generated by Django 6.0.5 on 2026-05-29 05:01

import django.db.models.deletion
import lawofmessiah_app.models.bible_books
import url_or_relative_url_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleTranslationMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_id', models.CharField(default='', max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('file', models.ImageField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='LawOfMessiah',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('source_dataset', models.CharField(choices=[('ot', 'Old Testament'), ('nt', 'New Testament')], default='ot', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('commandment', models.TextField(blank=True, default='')),
                ('commandment_subtitles', models.JSONField(blank=True, default=list)),
                ('commandment_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('both', 'Positive & Negative')], default='positive', max_length=64)),
                ('commandment_form', models.CharField(blank=True, choices=[('', '-'), ('explicit', 'Explicit'), ('implied', 'Implied')], default='', max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=256)),
                ('is_unique', models.BooleanField(default=False)),
                ('commentary_rudolph', models.TextField(blank=True, default='')),
                ('commentary_juster', models.TextField(blank=True, default='')),
                ('classical_commentators', models.TextField(blank=True, default='')),
                ('commandments_related_ot', models.JSONField(blank=True, default=list)),
                ('commandments_related_nt', models.JSONField(blank=True, default=list)),
                ('related_lawofmessiah', models.JSONField(blank=True, default=list)),
                ('maimonides', models.JSONField(blank=True, default=list)),
                ('meir', models.JSONField(blank=True, default=list)),
                ('chinuch', models.JSONField(blank=True, default=list)),
                ('ncla', models.JSONField(blank=True, default=list)),
                ('ncla_deviation', models.BooleanField(default=False)),
                ('classical_commandment', models.BooleanField(default=False)),
                ('source', models.TextField(blank=True, default='')),
                ('copyright', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Law of Messiah',
                'verbose_name_plural': 'Law of Messiah',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Maimonides',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('commandment_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=32)),
                ('commandment', models.TextField(blank=True, default='')),
                ('meir', models.JSONField(blank=True, default=list)),
                ('chinuch', models.JSONField(blank=True, default=list)),
                ('rudolph', models.JSONField(blank=True, default=list)),
                ('scriptures', models.JSONField(blank=True, default=list)),
                ('meir_scriptures', models.JSONField(blank=True, default=list)),
                ('chinuch_scriptures', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Maimonides commandment',
                'verbose_name_plural': 'Maimonides Commandments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', url_or_relative_url_field.fields.URLOrRelativeURLField()),
            ],
        ),
        migrations.CreateModel(
            name='LawOfMessiahBibleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('key_nt_scriptures', 'Key NT Scriptures'), ('key_ot_scriptures', 'Key OT Scriptures'), ('supportive_nt_scriptures', 'Supportive NT Scriptures'), ('supportive_ot_scriptures', 'Supportive OT Scriptures')], max_length=32)),
                ('book', models.CharField(choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus'), ('Leviticus', 'Leviticus'), ('Numbers', 'Numbers'), ('Deuteronomy', 'Deuteronomy'), ('Joshua', 'Joshua'), ('Judges', 'Judges'), ('Ruth', 'Ruth'), ('SamuelFirstBook', '1 Samuel'), ('SamuelSecondBook', '2 Samuel'), ('KingsFirstBook', '1 Kings'), ('KingsSecondBook', '2 Kings'), ('ChroniclesFirstBook', '1 Chronicles'), ('ChroniclesSecondBook', '2 Chronicles'), ('Ezra', 'Ezra'), ('Nehemiah', 'Nehemiah'), ('Esther', 'Esther'), ('Job', 'Job'), ('Psalms', 'Psalms'), ('Proverbs', 'Proverbs'), ('Ecclesiastes', 'Ecclesiastes'), ('SongOfSolomon', 'Song of Solomon'), ('Isaiah', 'Isaiah'), ('Jeremiah', 'Jeremiah'), ('Lamentations', 'Lamentations'), ('Ezekiel', 'Ezekiel'), ('Daniel', 'Daniel'), ('Hosea', 'Hosea'), ('Joel', 'Joel'), ('Amos', 'Amos'), ('Obadiah', 'Obadiah'), ('Jonah', 'Jonah'), ('Micah', 'Micah'), ('Nahum', 'Nahum'), ('Habakkuk', 'Habakkuk'), ('Zephaniah', 'Zephaniah'), ('Haggai', 'Haggai'), ('Zechariah', 'Zechariah'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('Acts', 'Acts'), ('Romans', 'Romans'), ('CorinthiansFirstBook', '1 Corinthians'), ('CorinthiansSecondBook', '2 Corinthians'), ('Galatians', 'Galatians'), ('Ephesians', 'Ephesians'), ('Philippians', 'Philippians'), ('Colossians', 'Colossians'), ('ThessaloniansFirstBook', '1 Thessalonians'), ('ThessaloniansSecondBook', '2 Thessalonians'), ('TimothyFirstBook', '1 Timothy'), ('TimothySecondBook', '2 Timothy'), ('Titus', 'Titus'), ('Philemon', 'Philemon'), ('Hebrews', 'Hebrews'), ('James', 'James'), ('PeterFirstBook', '1 Peter'), ('PeterSecondBook', '2 Peter'), ('JohnFirstBook', '1 John'), ('JohnSecondBook', '2 John'), ('JohnThirdBook', '3 John'), ('Jude', 'Jude'), ('Revelation', 'Revelation')], default=lawofmessiah_app.models.bible_books.BibleBooks['Genesis'], help_text='The bible book like Genesis, Exodus, etc.', max_length=32)),
                ('begin_chapter', models.IntegerField(default=0)),
                ('begin_verse', models.IntegerField(default=0)),
                ('end_chapter', models.IntegerField(default=0)),
                ('end_verse', models.IntegerField(default=0)),
                ('law_of_messiah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_reference_rows', to='commandments_app.lawofmessiah')),
            ],
            options={
                'ordering': ['reference_type', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LawOfMessiahDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('media_type', models.CharField(choices=[('drawing', 'Drawing'), ('song', 'Song'), ('superbook', 'Superbook'), ('henkieshow', 'Henkieshow'), ('movie', 'Movie'), ('shortmovie', 'ShortMovie'), ('wajvideo', 'WaJVideo'), ('sermon', 'Sermon'), ('picture', 'Picture'), ('testimony', 'Testimony'), ('blog', 'Blog'), ('book', 'Book')], default='drawing', max_length=32)),
                ('target_audience', models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32)),
                ('author', models.CharField(default='', max_length=64)),
                ('img_url', url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, default='', null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('language', models.CharField(choices=[('any', 'Language independent'), ('unknown', 'Language unknown'), ('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('ht', 'Haitian Creole'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=8)),
                ('is_public', models.BooleanField(default=False)),
                ('law_of_messiah', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='commandments_app.lawofmessiah')),
            ],
            options={
                'abstract': False,
                'unique_together': {('law_of_messiah', 'media_type', 'title', 'url', 'img_url', 'author', 'language', 'target_audience')},
            },
        ),
        migrations.CreateModel(
            name='MediaResource',
            fields=[
            ],
            options={
                'verbose_name': 'Media Resource',
                'verbose_name_plural': 'Media Resources',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commandments_app.lawofmessiahdrawing',),
        ),
        migrations.CreateModel(
            name='MaimonidesBibleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('maimonides_scriptures', 'Maimonides Scriptures'), ('meir_scriptures', 'Meir Scriptures'), ('chinuch_scriptures', 'HaChinuch Scriptures')], max_length=32)),
                ('source_code', models.CharField(blank=True, default='', max_length=32)),
                ('book', models.CharField(choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus'), ('Leviticus', 'Leviticus'), ('Numbers', 'Numbers'), ('Deuteronomy', 'Deuteronomy'), ('Joshua', 'Joshua'), ('Judges', 'Judges'), ('Ruth', 'Ruth'), ('SamuelFirstBook', '1 Samuel'), ('SamuelSecondBook', '2 Samuel'), ('KingsFirstBook', '1 Kings'), ('KingsSecondBook', '2 Kings'), ('ChroniclesFirstBook', '1 Chronicles'), ('ChroniclesSecondBook', '2 Chronicles'), ('Ezra', 'Ezra'), ('Nehemiah', 'Nehemiah'), ('Esther', 'Esther'), ('Job', 'Job'), ('Psalms', 'Psalms'), ('Proverbs', 'Proverbs'), ('Ecclesiastes', 'Ecclesiastes'), ('SongOfSolomon', 'Song of Solomon'), ('Isaiah', 'Isaiah'), ('Jeremiah', 'Jeremiah'), ('Lamentations', 'Lamentations'), ('Ezekiel', 'Ezekiel'), ('Daniel', 'Daniel'), ('Hosea', 'Hosea'), ('Joel', 'Joel'), ('Amos', 'Amos'), ('Obadiah', 'Obadiah'), ('Jonah', 'Jonah'), ('Micah', 'Micah'), ('Nahum', 'Nahum'), ('Habakkuk', 'Habakkuk'), ('Zephaniah', 'Zephaniah'), ('Haggai', 'Haggai'), ('Zechariah', 'Zechariah'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('Acts', 'Acts'), ('Romans', 'Romans'), ('CorinthiansFirstBook', '1 Corinthians'), ('CorinthiansSecondBook', '2 Corinthians'), ('Galatians', 'Galatians'), ('Ephesians', 'Ephesians'), ('Philippians', 'Philippians'), ('Colossians', 'Colossians'), ('ThessaloniansFirstBook', '1 Thessalonians'), ('ThessaloniansSecondBook', '2 Thessalonians'), ('TimothyFirstBook', '1 Timothy'), ('TimothySecondBook', '2 Timothy'), ('Titus', 'Titus'), ('Philemon', 'Philemon'), ('Hebrews', 'Hebrews'), ('James', 'James'), ('PeterFirstBook', '1 Peter'), ('PeterSecondBook', '2 Peter'), ('JohnFirstBook', '1 John'), ('JohnSecondBook', '2 John'), ('JohnThirdBook', '3 John'), ('Jude', 'Jude'), ('Revelation', 'Revelation')], default=lawofmessiah_app.models.bible_books.BibleBooks['Genesis'], help_text='The bible book like Genesis, Exodus, etc.', max_length=32)),
                ('begin_chapter', models.IntegerField(default=0)),
                ('begin_verse', models.IntegerField(default=0)),
                ('end_chapter', models.IntegerField(default=0)),
                ('end_verse', models.IntegerField(default=0)),
                ('maimonides', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_reference_rows', to='commandments_app.maimonides')),
            ],
            options={
                'ordering': ['reference_type', 'source_code', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse', 'id'],
            },
        ),
    ]
