# Generated by Django 6.1 on 2026-08-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0002_bibletranslationusagedaily_pagevisitdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Bible',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='bibletranslationusagedaily',
            new_name='commandment_usage_d_59f4cd_idx',
            old_name='commandments_app_bible_usage_daily_idx',
        ),
        migrations.RenameIndex(
            model_name='bibletranslationusagedaily',
            new_name='commandment_usage_d_ae401a_idx',
            old_name='commandments_app_bible_usage_source_idx',
        ),
        migrations.RenameIndex(
            model_name='bibletranslationusagedaily',
            new_name='commandment_bible_i_319378_idx',
            old_name='commandments_app_bible_usage_user_idx',
        ),
        migrations.RenameIndex(
            model_name='pagevisitdaily',
            new_name='commandment_usage_d_66dfac_idx',
            old_name='commandments_app_page_visit_date_path_idx',
        ),
        migrations.RenameIndex(
            model_name='pagevisitdaily',
            new_name='commandment_usage_d_645ac2_idx',
            old_name='commandments_app_page_visit_date_lang_idx',
        ),
        migrations.RenameIndex(
            model_name='pagevisitdaily',
            new_name='commandment_page_pa_2525f3_idx',
            old_name='commandments_app_page_visit_path_user_idx',
        ),
    ]
